### ISSUE TITLE
Initial setup issues

### ISSUE THREAD

**Issue by alemuro** [grafana/home-assistant-addons#20]
Hello! 

Many thanks for the integration. I want to expose the CPU and MEM consumption of all Home Assistant containers (running with Hassio/HA OS), but unfortunately after configuring your addon I faced the following error, and the addon don't manage to start:

```
Error: grafana_cloud:12:3: Failed to build component: building component: unexpected status code 403 Forbidden
Error: grafana_cloud:46:16: json_decode unexpected end of JSON input
Error: grafana_cloud:52:18: json_decode unexpected end of JSON input
Error: grafana_cloud:35:13: json_decode unexpected end of JSON input
Error: grafana_cloud:23:13: json_decode unexpected end of JSON input
Error: grafana_cloud:83:3: Failed to evaluate node for config block: decoding configuration: grafana_cloud:84:13: json_decode unexpected end of JSON input
Error: grafana_cloud:60:13: json_decode unexpected end of JSON input
ts=2024-11-23T10:36:06.723992921Z level=error msg="failed to start reporter" err="context canceled"
interrupt received
```

I have prometheus configured as the following config:

```yaml
prometheus:
  namespace: ha
  filter:
    include_entity_globs:
      - sensor.*_cpu_percent
      - sensor.*_memory_percent
```

As can be seen on the following screenshot, there should be sensors matching these regex:

![Image](https://github.com/user-attachments/assets/92ea77d8-42f8-4962-a4de-a401a7eb72ab)

Do you know what can cause this issue? Am I doing something wrong?

BTW, when creating the _Access Policy_ I wasn't able to grant "read" permissions over the Stack scope. I guess this is something that has changed from the Grafana Cloud side and I assume this permission is granted by default.

I'm running:
* Core: 2024.11.3
* Supervisor: 2024.11.4
* Operating System: 13.2
* Grafana Cloud addon 0.1.1

Many thanks in advance! 🙏

**Comment by alemuro** [comment]
Seems the error is produced by the upstream Alloy module, reported here: 

https://github.com/grafana/alloy-modules/issues/56

**Comment by alemuro** [comment]
Okay.. user error. The stack permission can be added additionally, my fault. Closing this!

**Comment by smartcuc** [comment]
Hi alemuro,
As I'm facing the same issue, can you recall how you got this fixed?
Many thanks!!
